feat: support linux(loong64)
cloudwego/netpoll pull request #199
Opened 2022-09-15 04:34 UTC by abner-chenc

2022-09-15 04:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cloudwego/netpoll?pullRequest=199) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cloudwego/netpoll?pullRequest=199) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cloudwego/netpoll?pullRequest=199) it.</sub>

2022-09-15 04:38 UTC, abner-chenc commented
go version go1.19 linux/loong64
go test -v ./...
```
=== RUN   TestErrno
    connection_errors_test.go:30: error1=connection has been closed when next
    connection_errors_test.go:35: error2=broken pipe when flush
--- PASS: TestErrno (0.00s)
=== RUN   TestConnectionWrite
--- PASS: TestConnectionWrite (0.07s)
=== RUN   TestConnectionLargeWrite
    connection_test.go:67: skip large write test for ci job
--- SKIP: TestConnectionLargeWrite (0.00s)
=== RUN   TestConnectionRead
--- PASS: TestConnectionRead (0.77s)
=== RUN   TestConnectionReadAfterClosed
--- PASS: TestConnectionReadAfterClosed (0.00s)
=== RUN   TestConnectionWaitReadHalfPacket
--- PASS: TestConnectionWaitReadHalfPacket (0.00s)
=== RUN   TestReadTimer
--- PASS: TestReadTimer (0.00s)
=== RUN   TestReadTrigger
--- PASS: TestReadTrigger (0.00s)
=== RUN   TestLargeBufferWrite
--- PASS: TestLargeBufferWrite (0.88s)
=== RUN   TestConnectionLargeMemory
--- PASS: TestConnectionLargeMemory (1.07s)
=== RUN   TestSetTCPNoDelay
--- PASS: TestSetTCPNoDelay (0.00s)
=== RUN   TestConnectionUntil
--- PASS: TestConnectionUntil (1.19s)
=== RUN   TestBookSizeLargerThanMaxSize
--- PASS: TestBookSizeLargerThanMaxSize (5.64s)
=== RUN   TestPersistFDOperator
--- PASS: TestPersistFDOperator (0.01s)
=== RUN   TestDialerTCP
--- PASS: TestDialerTCP (0.00s)
=== RUN   TestDialerUnix
2022/09/18 09:10:02 readv(fd=23) failed: connection reset by peer
--- PASS: TestDialerUnix (0.00s)
=== RUN   TestDialerFdAlloc
--- PASS: TestDialerFdAlloc (0.15s)
=== RUN   TestFDClose
--- PASS: TestFDClose (1.00s)
=== RUN   TestDialerThenClose
--- PASS: TestDialerThenClose (0.11s)
=== RUN   TestListenerDialer
--- PASS: TestListenerDialer (0.21s)
=== RUN   TestConvertListener
--- PASS: TestConvertListener (0.00s)
=== RUN   TestZeroTimer
--- PASS: TestZeroTimer (0.00s)
=== RUN   TestRuntimePoll
--- PASS: TestRuntimePoll (0.00s)
=== RUN   TestEqual
--- PASS: TestEqual (0.00s)
=== RUN   TestOnConnect
--- PASS: TestOnConnect (1.04s)
=== RUN   TestOnConnectWrite
--- PASS: TestOnConnectWrite (1.00s)
=== RUN   TestGracefulExit
--- PASS: TestGracefulExit (10.00s)
=== RUN   TestCloseCallbackWhenOnRequest
--- PASS: TestCloseCallbackWhenOnRequest (0.00s)
=== RUN   TestCloseCallbackWhenOnConnect
--- PASS: TestCloseCallbackWhenOnConnect (0.00s)
=== RUN   TestCloseAndWrite
--- PASS: TestCloseAndWrite (0.10s)
=== RUN   TestLinkBuffer
--- PASS: TestLinkBuffer (0.00s)
=== RUN   TestLinkBufferWithInvalid
--- PASS: TestLinkBufferWithInvalid (0.00s)
=== RUN   TestLinkBufferIndex
--- PASS: TestLinkBufferIndex (0.00s)
=== RUN   TestLinkBufferRefer
--- PASS: TestLinkBufferRefer (0.00s)
=== RUN   TestLinkBufferResetTail
1: 01
2: 01
--- PASS: TestLinkBufferResetTail (0.00s)
=== RUN   TestWriteBuffer
--- PASS: TestWriteBuffer (0.00s)
=== RUN   TestWriteBinary
--- PASS: TestWriteBinary (0.00s)
=== RUN   TestWriteDirect
--- PASS: TestWriteDirect (0.00s)
=== RUN   TestUnsafeStringToSlice
--- PASS: TestUnsafeStringToSlice (0.00s)
=== RUN   TestLinkBufferIndexByte
--- PASS: TestLinkBufferIndexByte (0.01s)
=== RUN   TestZCReader
--- PASS: TestZCReader (0.00s)
=== RUN   TestZCWriter
--- PASS: TestZCWriter (0.00s)
=== RUN   TestZCEOF
--- PASS: TestZCEOF (0.00s)
=== RUN   TestIOReadWriter
--- PASS: TestIOReadWriter (0.00s)
=== RUN   TestIOReadWriter2
--- PASS: TestIOReadWriter2 (0.00s)
=== RUN   TestPollManager
--- PASS: TestPollManager (0.01s)
=== RUN   TestPollManagerReset
--- PASS: TestPollManagerReset (0.00s)
=== RUN   TestPollTrigger
    poll_test.go:30: 
--- SKIP: TestPollTrigger (0.00s)
=== RUN   TestPollMod
--- PASS: TestPollMod (0.05s)
=== RUN   TestPollClose
--- PASS: TestPollClose (0.00s)
=== RUN   TestIovecs
--- PASS: TestIovecs (0.53s)
=== RUN   TestWritev
    sys_exec_test.go:93: READ first linesecond linethird line
--- PASS: TestWritev (0.00s)
=== RUN   TestReadv
    sys_exec_test.go:120: READ [0] 
    sys_exec_test.go:120: READ [1] 
    sys_exec_test.go:120: READ [2] 
    sys_exec_test.go:120: READ [3] 
--- PASS: TestReadv (0.00s)
=== RUN   TestSendmsg
    sys_exec_test.go:141: READ first linesecond linethird line
--- PASS: TestSendmsg (0.00s)
PASS
ok  	github.com/cloudwego/netpoll	23.862s
=== RUN   TestShardQueue
--- PASS: TestShardQueue (0.00s)
PASS
ok  	github.com/cloudwego/netpoll/mux	0.025s

```

2022-10-25 03:00 UTC, Hchenn approved these changes

2022-10-25 03:04 UTC, joway commented on sys_epoll_linux_loong64.go
> +// Copyright 2022 Loongson Inc.
```suggestion
// Copyright 2021 CloudWeGo Authors
```

2022-11-09 11:10 UTC, abner-chenc commented on sys_epoll_linux_loong64.go
> +// Copyright 2022 Loongson Inc.
Thanks, I have updated it.

2022-11-10 02:45 UTC, joway requested changes

2022-11-10 02:45 UTC, joway commented on sys_epoll_linux_loong64.go
> +// Copyright 2022 CloudWeGo Authors
Error: ./sys_epoll_linux_loong64.go:22:7: EPOLLET redeclared in this block

add long64 build tag here?

2022-11-10 07:37 UTC, abner-chenc commented on sys_epoll_linux_loong64.go
> +// Copyright 2022 CloudWeGo Authors
我理解这个应该不需要吧，Go的条件编译规则已经限制了这个文件仅仅在在linux/loong64编译使用。

2022-11-10 07:38 UTC, joway commented on sys_epoll_linux_loong64.go
> +// Copyright 2022 CloudWeGo Authors
@abner-chenc 可以看 CI 挂掉的错误日志

2022-11-10 08:11 UTC, abner-chenc commented on sys_epoll_linux_loong64.go
> +// Copyright 2022 CloudWeGo Authors
不好意思， 我已经加了tag（新旧两种格式）。  这个是因为CI的Go版本是1.16的， 而loong64这个关键字是1.17才引入的， 所以出现这个错误。

2022-11-11 06:43 UTC, joway approved these changes

2022-11-11 06:43 UTC, joway commented
thanks for your contribution

2022-11-11 06:44 UTC, merged