fix: 修复sys_exec_test.go函数中TestReadv测试函数使用错误
cloudwego/netpoll pull request #297
Opened 2023-12-06 13:23 UTC by BinaryOracle

# 问题描述

项目路径下提供了一个测试用例文件: sys_exec_test.go  , 其中提供了一个测试函数TestReadv，用于测试Readv系统调用：

```go
func TestReadv(t *testing.T) {
	// 1. 向fd中写入数据
	r, w := GetSysFdPairs()
	vs := [][]byte{
		[]byte("first line"),  // len=10
		[]byte("second line"), // len=11
		[]byte("third line"),  // len=10
	}
	w1, _ := syscall.Write(w, vs[0])
	w2, _ := syscall.Write(w, vs[1])
	w3, _ := syscall.Write(w, vs[2])
	Equal(t, w1+w2+w3, 31)

	// 2. 准备bs和ivs缓冲区
	var barrier = barrier{}
	barrier.bs = [][]byte{
		make([]byte, 0),
		make([]byte, 10),
		make([]byte, 11),
		make([]byte, 10),
	}
	barrier.ivs = make([]syscall.Iovec, len(barrier.bs))
	// 3. 调用readv系统调用,读取数据到ivs , ivs缓冲区指针指向了bs
	rn, err := readv(r, barrier.bs, barrier.ivs)
	MustNil(t, err)
	Equal(t, rn, 31)
	// 4. 打印bs缓冲区中的数据
	for i, v := range barrier.bs {
		t.Logf("READ [%d] %s", i, v)
	}
}
```
在没有修改前，readv的源码如下:
```go
// readv wraps the readv system call.
// return 0, nil means EOF.
func readv(fd int, bs [][]byte, ivs []syscall.Iovec) (n int, err error) {
        // 依次为每个ivs[i].base 与 bs[i] 建立映射关系
	iovLen := iovecs(bs, ivs)
	if iovLen == 0 {
		return 0, nil
	}
	// syscall
	r, _, e := syscall.RawSyscall(syscall.SYS_READV, uintptr(fd), uintptr(unsafe.Pointer(&ivs[0])), uintptr(iovLen))
        // 此处会清空bs和ivs缓冲区
	resetIovecs(bs, ivs[:iovLen])
	if e != 0 {
		return int(r), syscall.Errno(e)
	}
	return int(r), nil
}
```
最终输出的结果为 , 缓冲区中的数据为空，都被清空了，不符合预期:
```go
=== RUN   TestReadv
    sys_exec_test.go:120: READ [0] 
    sys_exec_test.go:120: READ [1] 
    sys_exec_test.go:120: READ [2] 
    sys_exec_test.go:120: READ [3] 
--- PASS: TestReadv (0.00s)
PASS
```
# 解决办法

将readv中清空缓冲区的方法调用移除:
```go
// readv wraps the readv system call.
// return 0, nil means EOF.
func readv(fd int, bs [][]byte, ivs []syscall.Iovec) (n int, err error) {
	iovLen := iovecs(bs, ivs)
	if iovLen == 0 {
		return 0, nil
	}
	// syscall
	r, _, e := syscall.RawSyscall(syscall.SYS_READV, uintptr(fd), uintptr(unsafe.Pointer(&ivs[0])), uintptr(iovLen))
	if e != 0 {
		return int(r), syscall.Errno(e)
	}
	return int(r), nil
}
```

再次运行测试用例，输出如下:

```go
=== RUN   TestReadv
    sys_exec_test.go:124: READ [0] 
    sys_exec_test.go:124: READ [1] first line
    sys_exec_test.go:124: READ [2] second line
    sys_exec_test.go:124: READ [3] third line
--- PASS: TestReadv (0.00s)
PASS
```

2023-12-06 13:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cloudwego/netpoll?pullRequest=297) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cloudwego/netpoll?pullRequest=297) before we can accept your contribution.<br/><hr/>**zhandaohong** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cloudwego/netpoll?pullRequest=297) it.</sub>

2023-12-07 03:03 UTC, joway commented
@BinaryOracle 这个其实是这段测试有点问题。原本的代码没问题。之所以要reset，是因为 barrier 不能持有原始 []byte 的引用，否则这段 []byte 永远不能被 GC

2023-12-07 03:04 UTC, joway requested changes
可以修改 TestReadv ，独立创建每一个 []byte 的变量，然后直接读取变量中的内容。而不是读取 [][]byte 里的内容

2023-12-08 03:10 UTC, joway commented
@BinaryOracle Hi，能再辛苦你能签署下这个吗？
<img width="897" alt="image" src="https://github.com/cloudwego/netpoll/assets/8353464/ae09a1d2-481d-4461-adbe-ef6e6588b60b">

2023-12-08 03:11 UTC, BinaryOracle commented
> @BinaryOracle Hi，能再辛苦你能签署下这个吗？ <img alt="image" width="897" src="https://private-user-images.githubusercontent.com/8353464/288951067-ae09a1d2-481d-4461-adbe-ef6e6588b60b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDUzNjcsIm5iZiI6MTcwMjAwNTA2NywicGF0aCI6Ii84MzUzNDY0LzI4ODk1MTA2Ny1hZTA5YTFkMi00ODFkLTQ0NjEtYWRiZS1lZjZlNjU4OGI2MGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDhUMDMxMTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzRkMDg1YmJkNDI5ZDJhMjIwODkwNzQwOTdmYmUzNzUwNDg0ZTcyNjViNzlhOGZmZmNhZmQ5ODRkODcyZjAyOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TizcLP5uP7Ac5nsCjHA8C_MRJ8bZWMuZBNAGUO36ju4">

好

2023-12-08 05:03 UTC, BinaryOracle commented
> @BinaryOracle Hi，能再辛苦你能签署下这个吗？ <img alt="image" width="897" src="https://private-user-images.githubusercontent.com/8353464/288951067-ae09a1d2-481d-4461-adbe-ef6e6588b60b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDcxNzgsIm5iZiI6MTcwMjAwNjg3OCwicGF0aCI6Ii84MzUzNDY0LzI4ODk1MTA2Ny1hZTA5YTFkMi00ODFkLTQ0NjEtYWRiZS1lZjZlNjU4OGI2MGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDhUMDM0MTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWEzMTMxNDQxZjE5NjYwNzlmNWE4MDY3MTE3N2U1NTA4YTJlNTgxNDZlNTgzNzRlZWM0YjkxOGQwNTMzODc2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UzxxAqfNIsdYR3FQ4Q12VQ02Mbq1f5ul7i9S8nVIxsM">

我看签署了CLA之后，但是显示处于pending状态:

<img width="549" alt="image" src="https://github.com/cloudwego/netpoll/assets/86190302/7cec6a04-9d06-40e9-a043-e34cf5f058ed">

然后我这边协议签署文件发送到对应的邮箱了,这边还需要做什么吗？

<img width="676" alt="image" src="https://github.com/cloudwego/netpoll/assets/86190302/a3eea036-25df-4614-80a5-932459364031">

2023-12-11 06:10 UTC, joway commented
<img width="969" alt="image" src="https://github.com/cloudwego/netpoll/assets/8353464/eba306f3-388f-443e-b4cd-ee8116663c2b">
@BinaryOracle 你提交commit用的邮箱应该不是你github的邮箱

2023-12-14 15:28 UTC, BinaryOracle commented
> <img alt="image" width="969" src="https://private-user-images.githubusercontent.com/8353464/289440666-eba306f3-388f-443e-b4cd-ee8116663c2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1Njc5MjksIm5iZiI6MTcwMjU2NzYyOSwicGF0aCI6Ii84MzUzNDY0LzI4OTQ0MDY2Ni1lYmEzMDZmMy0zODhmLTQ0M2UtYjRjZC1lZTgxMTY2NjNjMmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMTUyNzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2IyZTA3NGZjYzFmNjgxZDk0NWMwNjU4ZjYzYmVlNjlkMDZkYTg2MjhkNjlmNGQ1M2QwZGM1YjEwOTBiMTliMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Nj3oxU8-guIx7KdUO4w08SrsMm104_G6BvWc2PL_KyA"> @BinaryOracle 你提交commit用的邮箱应该不是你github的邮箱

提交代码的邮箱没认证，目前已经认证通过了

2024-01-23 07:15 UTC, joway approved these changes

2024-01-23 07:16 UTC, merged